const fs=require('fs');
const vm=require('vm');
const path=require('path');
const root=path.resolve(__dirname,'..');
const files=['js/00-balance.js','js/00-icons.js','js/01-data-core.js','js/02-data-content.js','js/03-state.js','js/04-systems.js','js/08-battle.js'];
const source=files.map(f=>fs.readFileSync(path.join(root,f),'utf8')).join('\n')+`
globalThis.__test={GB,BIOME_MIN_LEVEL,geneMult,combatPower,combatRisk,mutateCost,battleRewardFor,arenaOfferDragon};`;
const sandbox={console,Math,Date,setTimeout:()=>0,clearTimeout:()=>{},navigator:{},document:{},window:{}};
vm.createContext(sandbox);
vm.runInContext(source,sandbox,{filename:'draconis-test-bundle.js'});
const T=sandbox.__test;
const assert=(ok,msg)=>{if(!ok)throw new Error(msg);};
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
const css=fs.readFileSync(path.join(root,'css/style.css'),'utf8');
const tokens=fs.readFileSync(path.join(root,'css/tokens.css'),'utf8');
const flight=fs.readFileSync(path.join(root,'js/07-flight.js'),'utf8');
const hub=fs.readFileSync(path.join(root,'js/06c-hubmap.js'),'utf8');

assert(T.GB.Release.version==='3.0.0','release version');
assert(JSON.stringify(Array.from(T.BIOME_MIN_LEVEL))===JSON.stringify([0,1,22,55]),'biome progression');
assert(Math.abs(T.geneMult(3)-1)<1e-9,'neutral gene must be 1.0');
assert(Math.abs(T.geneMult(6)-1.15)<1e-9,'max gene must be bounded');

const base={id:'ember',level:20,xp:0,curHp:999,morph:'common',genes:{atk:3,def:3,hp:3,spd:3},nature:'balanced'};
const stronger={...base,level:22};
assert(T.combatPower(stronger)>T.combatPower(base),'combat power must grow with stats');
assert(T.combatRisk(base,stronger).ratio>1,'risk must use combat power');

const common={id:'ember',level:20,morph:'common'};
const rare={id:'voidmaw',level:20,morph:'common'};
const commonReward=T.battleRewardFor(base,common);
const rareReward=T.battleRewardFor(base,rare);
assert(rareReward/commonReward<1.3,'rarity must not directly multiply reward');

assert(T.mutateCost({mutations:99,geneGrowth:0})===8,'failed mutations must not inflate cost');
assert(T.mutateCost({geneGrowth:99})===40,'mutation cost must be capped');
assert(T.GB.Battle.matchmaking.rewardBands[2]<=1.12,'danger reward must not dominate');

const oldIdle=.32*100*300;
const newIdle=T.GB.Economy.idleBasePerMinute*Math.sqrt(100)*T.GB.Economy.idleLevelScale*300;
assert(newIdle<oldIdle*.15,'late idle income must be bounded');

assert(!/[РС][РСЃРµР°Р»]/.test(index),'index must not contain common mojibake');
assert((index.match(/class="tabbtn/g)||[]).length===5,'five navigation buttons must render');
assert(index.includes('data-tab="hub"     title="Поселение"'),'hub must be named Settlement');
assert(index.includes('data-tab="lair"    title="Логово"'),'dragon home must be named Lair');
assert(!index.includes('no-cache, no-store'),'production HTML must allow asset caching');
const versions=[...index.matchAll(/[?&]v=([^"'&]+)/g)].map(m=>m[1]);
assert(versions.length>0&&versions.every(v=>v==='300'),'static asset versions must be unified');
assert(css.includes('repeat(5,minmax(0,1fr))'),'navigation must use five equal columns');
assert(css.includes("fonts/Literata-Variable.ttf"),'local Cyrillic font must be bundled');
assert(fs.existsSync(path.join(root,'fonts/Literata-Variable.ttf')),'local font file must exist');
assert(index.includes('css/tokens.css?v=300'),'design tokens must be connected after legacy styles');
assert(tokens.includes('--ds-paper:#f4e7c8')&&tokens.includes('--ds-emerald:#2f7d68'),'storybook palette tokens must exist');
assert(tokens.includes('--ds-touch:48px'),'minimum touch target must be tokenized');
assert(tokens.includes('body.a11y-motion-off'),'manual reduced-motion mode must exist');
assert(flight.includes('images/arcade_${sp.el}.webp'),'flight and battle must use transparent dragon assets');
assert(!flight.includes('images/fly_${sp.el}_'),'opaque flight backgrounds must not be used as sprites');
assert(hub.includes('hub-task-drawer')&&hub.includes('hub-service-bar'),'hub task drawer and service bar must render');
assert(hub.includes('<b>Сегодня</b>')&&hub.includes('hubDailyClaim'),'hub must own daily tasks and daily reward');
const content=fs.readFileSync(path.join(root,'js/02-data-content.js'),'utf8');
const artifactBlock=content.slice(content.indexOf('const ARTIFACTS = ['),content.indexOf('// эффекты, которые не являются'));
assert((artifactBlock.match(/id:'/g)||[]).length===27,'all 27 artifacts must remain in catalog');
assert((artifactBlock.match(/artifact-game-icon/g)||[]).length===27,'all artifacts must use dedicated game icons');
const save=fs.readFileSync(path.join(root,'js/11-save-init.js'),'utf8');
assert(!save.includes('id="resetBtn"'),'daily rewards must not contain the reset action');
assert(save.includes('id="svReset"')&&save.includes('Удерживай 2 секунды'),'reset must live in save manager and require holding');
assert(!index.includes('panel--daily'),'lair HTML must not duplicate the daily task panel');
assert(save.includes('Посмотреть дела в поселении'),'lair gift view must route daily tasks back to the hub');
const nav=fs.readFileSync(path.join(root,'js/10-spire-codex.js'),'utf8');
assert(nav.includes('function switchBack()')&&nav.includes('viewTrail'),'secondary screens must return to their actual origin');
const systems=fs.readFileSync(path.join(root,'js/04-systems.js'),'utf8');
assert(systems.includes('a11y-motion-off')&&systems.includes('vibrationOff'),'motion and vibration preferences must be independent');
assert(systems.includes('const TUTORIALS=')&&systems.includes('function completeLesson'),'replayable action-based lesson registry must exist');
assert(systems.includes('function renderScreenHelp'),'context help button must exist');
assert(index.includes('data-ctab="tips"')&&index.includes('id="codexTips"'),'Vella tips must have a Codex section');
assert(nav.includes('function renderVellaTips')&&nav.includes('showLesson(b.dataset.tip,{replay:true})'),'Codex lessons must be replayable');
assert(nav.includes("renderScreenHelp(v)"),'every supported screen must refresh contextual help');
assert(save.includes('function renderStartEggHatch()')&&save.includes('starterEggHTML'),'onboarding must start with an interactive egg');
assert(save.includes("crack>=3")&&save.includes('crack-progress'),'starter egg must hatch in three readable stages');
assert(save.includes("timingAssists:2")&&save.includes("safeFlight:true"),'first-hour safety state must be initialized');
assert(save.includes('SETTLEMENT_NAMES')&&save.includes('STARTER_NAMES'),'text entry must have ready-made child-friendly defaults');
assert(flight.includes("S.firstHour&&S.firstHour.safeFlight"),'random choice threats must be disabled in the first expedition');
assert(flight.includes("S.firstHour.phase='first_battle'"),'first find must advance the onboarding route');
assert(fs.readFileSync(path.join(root,'js/08-battle.js'),'utf8').includes('const SPEED=assisted?60:100'),'first two timing actions must be 40 percent slower');
assert(save.includes('const WEEKLY_STEPS=')&&save.includes('function claimWeekly()'),'five-stage weekly expedition must exist');
assert(save.includes('streakShield')&&save.includes('мягкий откат вместо полного обнуления'),'login streak must forgive or soften missed days');
assert(save.includes('S.quests.every(x=>x.claimed)'),'finishing daily tasks must restore streak protection');
assert(hub.includes('Недельная экспедиция')&&hub.includes('hubWeeklyClaim'),'weekly progress must be visible and claimable in Today drawer');
const lair=fs.readFileSync(path.join(root,'js/05d-lairwell.js'),'utf8');
assert(lair.includes('ws-mood')&&lair.includes('_lairMood'),'selected dragon must communicate mood in plain language');

console.log('Draconis 3.0 release tests: OK');
